import SocketProvider from "@/components/ludo/SocketProvider";


export const metadata = {
  title: "Online Ludo Game",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <SocketProvider>{children}</SocketProvider>
  );
}
